# Copyright (c) HashiCorp, Inc.
# SPDX-License-Identifier: MPL-2.0

version: "2"
run:
  issues-exit-code: 1
  tests: true
output:
  formats:
    text:
      path: stdout
      print-linter-name: true
      print-issued-lines: true
linters:
  default: none
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unconvert
    - unused
  settings:
    errcheck:
      check-type-assertions: false
      check-blank: false
      exclude-functions:
        - fmt:.*
        - io/ioutil:^Read.*
        - io:Close
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      # Exclude bool check
      - linters:
          - staticcheck
        text: S(1002|1008|1021)
      # Exclude failing staticchecks for now
      - linters:
          - staticcheck
        text: 'SA(1006|1019|4006|4010|4017|5007|6005|9004):'
      - linters:
          - staticcheck
        text: 'ST(1005|1006|1019)'
      - linters:
          - staticcheck
        text: 'QF(1002|1004|1007|1008):'
      # Exclude lll issues for long lines with go:generate
      - linters:
          - lll
        source: '^//go:generate '
      - linters:
          - errcheck
        path: .*_test.go
    paths:
      - .*\.hcl2spec\.go$
      - third_party$
      - builtin$
      - examples$
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  uniq-by-line: true
formatters:
  enable:
    - goimports
  exclusions:
    generated: lax
    paths:
      - .*\.hcl2spec\.go$
      - third_party$
      - builtin$
      - examples$
