#
# This GitHub action runs Packer go tests across
# Windows runners.
#

name: "Go Test Windows"

on:
  push:
    branches:
      - 'main'
  pull_request:

permissions:
  contents: read

jobs:
  get-go-version:
    runs-on: ubuntu-latest
    outputs:
      go-version: ${{ steps.get-go-version.outputs.go-version }}
    steps:
      - uses: actions/checkout@8f4b7f84864484a7bf31766abe9204da3cbe65b3 # v3.5.0
      - name: 'Determine Go version'
        id: get-go-version
        run: |
          echo "Found Go $(cat .go-version)"
          echo "go-version=$(cat .go-version)" >> $GITHUB_OUTPUT
  windows-go-tests:
    needs:
      - get-go-version
    runs-on: windows-latest
    name: Windows Go tests
    steps:
      - uses: actions/checkout@8f4b7f84864484a7bf31766abe9204da3cbe65b3 # v3.5.0
      - uses: actions/setup-go@4d34df0c2316fe8122ab82dc22947d607c0c91f9 # v4.0.0
        with:
          go-version: ${{ needs.get-go-version.outputs.go-version }}
      - run: |
          echo "Testing with Go ${{ needs.get-go-version.outputs.go-version }}"
          go test -race -count 1 ./... -timeout=3m

